spring.application.name=app
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.javax.persistence.schema-generation.database.action=create
server.address=0.0.0.0



minio.endpoint=http://minio:9000
minio.public-endpoint=https://localhost/minio
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=trakker

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# ================================
# JWT ? chaves injetadas via variável de ambiente
# Nunca coloque os valores das chaves diretamente aqui em produção
# ================================
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.private-key=${JWT_PRIVATE_KEY}


#SMTP
# E-mail (exemplo com Gmail — veja abaixo para outros provedores)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=traker.noreply@gmail.com
spring.mail.password=ilkf lpks nvrf xsaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL do frontend (usada no link do e-mail)
app.frontend.url=https://localhost

management.endpoint.health.show-details=always
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health